project:
  type: book

book:
  title: "Introduction to musical corpus studies"
  author: "Fabian C. Moss"
  date: "2/13/2023"
  chapters:
    - index.qmd
    - syllabus.qmd
    - intro.qmd
    # - meter.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



